---
title: "Forest Plots BRCA2"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r libraries}
library(ggplot2)
library(patchwork)
library(readxl)
```

```{r read in files}
ukbb_malig <- read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/ukbb_brca2_malignancies.xlsx')
ukbb_ben <- read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/ukbb_brca2_benign.xlsx')
ghs_malig = read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/ghs_brca2_malig.xlsx')
ghs_ben = read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/ghs_brca2_benign.xlsx')
map = read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/benign_codes.xlsx')
ghs_malig_expand = read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/ghs_brca2_malig.xlsx', sheet = 2)
ghs_ben_expand = read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/ghs_brca2_benign.xlsx', sheet = 2)
ukbb_ben_expand <- read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/ukbb_brca2_benign.xlsx', sheet = 2)
ukbb_malig_expand = read_excel('/Users/orszagl2/Documents/Genetics/specific_cancers/ukbb_brca2_malignancies.xlsx', sheet = 2)
```

```{r write study columns}
ukbb_malig$study = "ukbb"
ukbb_ben$study = "ukbb"
ghs_malig$study = "ghs"
ghs_ben$study = "ghs"
ghs_malig_expand$study = "ghs"
ukbb_malig_expand$study = "ukbb"
ghs_ben_expand$study = "ghs"
ukbb_ben_expand$study = "ukbb"
```

```{r as factors}
ukbb_malig$Index <- factor(ukbb_malig$Index, levels=ukbb_malig$Index)
ghs_malig$Index <- factor(ghs_malig$Index, levels=ghs_malig$Index)
ukbb_ben$Index <- factor(ukbb_ben$Index, levels=ukbb_ben$Index)
ukbb_ben$lowCI = as.numeric(ukbb_ben$lowCI)
ukbb_ben$highCI = as.numeric(ukbb_ben$highCI)
ukbb_ben$OR = as.numeric(ukbb_ben$OR)
ghs_ben$Index <- factor(ghs_ben$Index, levels=ghs_ben$Index)
ghs_ben$lowCI = as.numeric(ghs_ben$lowCI)
ghs_ben$highCI = as.numeric(ghs_ben$highCI)
ghs_ben$OR = as.numeric(ghs_ben$OR)
```


```{r join malignant dataframes}
ukbb_malig$icd10 = c("All", 'Oral', "Digestive Organs", "Respiratory", "Bone", "Skin", "Soft Tissue", "Breast", "Female Genital", "Male Genital", "Urinary Tract", "CNS", "Endocrine", "Unspecified", "Lymphoid")
ghs_malig$icd10 = c("All",'Oral', "Digestive Organs", "Respiratory", "Bone", "Skin", "Soft Tissue", "Breast", "Female Genital", "Male Genital", "Urinary Tract", "CNS", "Endocrine", "Unspecified", "Lymphoid")
malig = rbind(ukbb_malig, ghs_malig)
malig = malig[-c(5, 17, 20), ]
```

```{r join benign dataframes}
benign = rbind(ukbb_ben, ghs_ben)
benign = benign%>%
  filter(ncases != 0)%>%
  mutate(OR_CI = paste0(round(OR, 2), "[", round(lowCI, 2), "-", round(highCI, 2), "]"))%>%
  left_join(map, by = "Index")
```

```{r join benign expanded dataframes}
benign_expand = rbind(ukbb_ben_expand, ghs_ben_expand)
benign_expand$lowCI = as.numeric(benign_expand$lowCI)
benign_expand$highCI = as.numeric(benign_expand$highCI)
benign_expand = benign_expand%>%
  filter(ncases != 0)%>%
  mutate(OR_CI = paste0(round(OR, 2), "[", round(lowCI, 2), "-", round(highCI, 2), "]"))%>%
  left_join(map, by = "Index")
```

```{r confidence intervals}
malig_expand = rbind(ukbb_malig_expand, ghs_malig_expand)
malig_expand$lowCI = as.numeric(malig_expand$lowCI)
malig_expand$highCI = as.numeric(malig_expand$highCI)
malig_expand = malig_expand%>%
  filter(ncases != 0)%>%
  mutate(OR_CI = paste0(round(OR, 2), "[", round(lowCI, 2), "-", round(highCI, 2), "]"))%>%
  left_join(map, by = "Index")
```

```{r}
forest_plot(malig, "BRCA 2 Malignancies", paste0(Index, ": ", icd10))
table_plot(malig, "BRCA 1 Malignancies")
```

```{r brca1 benign}
forest_plot(benign, "BRCA 2 Benign", paste0(Index, ": ", .))
```

```{r}
colnames(benign)[6] ='pv'
benign$p_value <- as.numeric(benign$p_value)
benign%>%filter(p_value<.05 | pv <.05)
```

```{r brca1 malignant expanded}
forest_plot(malig_expand, "BRCA 2 Malignant Expanded", paste0(Index, ": ", icd10))
```

```{r brca1 malignant expanded}
forest_plot(benign_expand, "BRCA 2 Benign Expanded", paste0(Index, ": ", .))
```